"""Generate Rust test vectors for the Fernet decryptor.

The key is generated fresh on every run and is unrelated to any real data: it
exists only so `crypt.rs` can be checked against Python's reference
implementation, which is what the old Streamlit app used to encrypt the DOP
password. If the app couldn't decrypt that ciphertext, nothing downstream
matters — so this is verified against the real thing rather than assumed.

Requires `cryptography` (already a dependency of the original app).

    python3 src-tauri/scripts/gen_fernet_vectors.py > src-tauri/src/crypt_vectors.rs

Then: cd src-tauri && cargo test
"""

from cryptography.fernet import Fernet

CASES = [
    ("ascii", "hunter2"),
    ("exact_block", "Y" * 16),      # exercises the PKCS7 full-padding block
    ("short_block", "Z" * 15),
    ("unicode", "p@ss\u20b9word"),
    ("long", "a1B2c3D4e5" * 12),
]


def rust_str(value: str) -> str:
    """A Rust string literal. Non-ASCII stays literal (Rust source is UTF-8);
    only backslash, quote and newline need escaping."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


key = Fernet.generate_key().decode()
fernet = Fernet(key.encode())

print("// Fernet test vectors — GENERATED, do not edit by hand.")
print("//")
print("// Produced by `scripts/gen_fernet_vectors.py` using Python's `cryptography`")
print("// library, so the Rust decryptor is checked against the reference")
print("// implementation. The key is a throwaway generated by that script and")
print("// protects nothing. Regular comments (not doc comments): this file is")
print("// pulled in with `include!`, where inner doc comments are not allowed.")
print()
print(f"pub const TEST_KEY: &str = {rust_str(key)};")
print()
print("// (name, plaintext, token)")
print("pub const TEST_VECTORS: &[(&str, &str, &str)] = &[")
for name, plaintext in CASES:
    token = fernet.encrypt(plaintext.encode()).decode()
    print(f"    ({rust_str(name)}, {rust_str(plaintext)}, {rust_str(token)}),")
print("];")
print()
print("// Encrypted under a *different* key — must be rejected.")
other = Fernet(Fernet.generate_key())
print(f"pub const FOREIGN_TOKEN: &str = {rust_str(other.encrypt(b'nope').decode())};")
