// Fernet test vectors — GENERATED, do not edit by hand.
//
// Produced by `gen_fernet_vectors.py` using Python's `cryptography`
// library, so the Rust decryptor is checked against the reference
// implementation. The key is a throwaway generated by that script and
// protects nothing. Regular comments (not doc comments): this file is
// pulled in with `include!`, where inner doc comments are not allowed.

pub const TEST_KEY: &str = "9lFT_9_wcx0-ZIpRvYAGMRoUDhU3qBDslipLOK5-ABM=";

// (name, plaintext, token)
pub const TEST_VECTORS: &[(&str, &str, &str)] = &[
    ("ascii", "hunter2", "gAAAAABqsS8YjcfA4kny7Qrv5v3C8tlZdpI-WcPPVCIpQF0r35__DJIPCtjUuytlmQsQie-EEzYLHNSw89108c3yVwIGhSAs1w=="),
    ("exact_block", "YYYYYYYYYYYYYYYY", "gAAAAABqsS8Ydv5lI6vT4kHL4s0XP27WlO2Px7p1A3tBB5j-C89xLBgL_ZS3-uvnRvN7ybmc8V9xLOKRbKzdHpVfuQ4vqbwnHwE3JiICqNAabI1LmIlXjrU="),
    ("short_block", "ZZZZZZZZZZZZZZZ", "gAAAAABqsS8Y-Vuh2USgHS2IiGP0nHA2nu86VkH0g-Wv4WVW34UZEsspfKESY470ZicD8K0PJ7qoiSvGfAIHSqsemuKqx3xi_g=="),
    ("unicode", "p@ss₹word", "gAAAAABqsS8YPZVZL_js5QcfV_CISSlNBHJmY8Of7oFgRr4XmVnwRZOS21MFwZlyaGiRJ5LABKBOFFEqlaRaooueb_B8sSmpuQ=="),
    ("long", "a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5a1B2c3D4e5", "gAAAAABqsS8YZ5020r2r_nizg4Jgh71nJ_Lko3jiGx8thfOPfG5d6kiSPPc8YH40Gq_PvVMJ-344zLgr7KrqhVc1FIPDT8la52RYirgIoKkRtAJDeWMPx7-I8ji2nPCdx_t-GIYdQ6fxEzbRkk4zKMcyA0inLxKrBs2kdK57HPIlK7FSDEONH4vhsCNQeo9QXaJaW3swzCTTd8Mf68MCXGKdYgYCjGJBlPT0jqGGFKu6EyXvQ9gH82k="),
];

// Encrypted under a *different* key — must be rejected.
pub const FOREIGN_TOKEN: &str = "gAAAAABqsS8YIda67rEKE6oRRaDS74qcIBxCILw7b4jLql0Hl4KJbUiW-hCwCKamhPhst0jB3Cb099yYuo8BOxQdMG2A-mtR1g==";
